# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Image::ObjectDetect
version:      0.11
version_from: lib/Image/ObjectDetect.pm
installdirs:  site
requires:
    Test::More:              0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
